#ifndef KAFKA_KAFKAERRORCODES_H
#define KAFKA_KAFKAERRORCODES_H

namespace Kafka {

enum KafkaErrorCodes {
    NO_ERROR = 0,
    UNKNOWN = -1,
    OFFSET_OUT_OF_RANGE = 1,
    INVALID_MESSAGE,
    UNKNOWN_TOPIC_OR_PARTITION,
    INVALID_MESSAGE_SIZE,
    LEADER_NOT_AVAILABLE,
    NOT_LEADER_FOR_PARTITION,
    REQUEST_TIMED_OUT,
    BROKER_NOT_AVAILABLE,
    REPLICA_NOT_AVAILABLE,
    MESSAGE_SIZE_TOO_LARGE,
    STALE_CONTROLLER_EPOCH_CODE,
    OFFSET_METADATA_TOO_LARGE_CODE
};
} //namespace Kafka

#endif //KAFKA_KAFKAERRORCODES_H
